# Filterbank config
filterbank:
  stft_kernel_size: 400
  stft_stride: 100
masknet:
  architecture: DCCRN-CL
data:
  task: enh_single
  train_dir: data/wav16k/max/train-360
  valid_dir: data/wav16k/max/dev
  sample_rate: 16000
  n_src: 1
  segment: 4
training:
  epochs: 1
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5